#!/bin/sh

servername="./apiserver"

param_1=$1

#Function
StartServer()
{	
	echo " >> start server"
	rm nohup.out -f
	echo "" >> nohup.out
	nohup $servername & > /dev/null 
	
	echo " >> Start Success!!! "
}

StopServer()
{
	echo " >> stop server"

	if [ $(GetPid ./apiserver) ]
	then
		echo " >>  Stop $servername...  PID="$(GetPid $servername)
		kill -9 $(GetPid $servername) 2> /dev/null
	fi

	echo " >> Stop Success!!! "
}

GetPid()
{
	echo "`ps aux | grep $1 | grep -v grep | grep -v /bin/sh | awk '{if($2>0){print $2;}{exit}}'`" | tr " " "\n"
}

GetTime()
{
	echo "`ps aux | grep $1 | grep -v grep | grep -v /bin/sh | awk '{print $9;}{exit}'`"
}

Info()
{
	echo " =========================================================================="
	printf " %-30s\t\t%-10s%-10s \n" [ServerName] [PID] [TIME]
	echo " --------------------------------------------------------------------------"
	pid=$( GetPid $servername )
	tm=$( GetTime $servername )
	printf " %-30s\t\t%-10s%-10s \n" $servername $pid $tm
	echo " =========================================================================="
}

Help()
{
	echo " ================== How To Use ==================" 
	echo " run <command> " 
	echo " Command List:" 
	echo " -s  or start    Start Server" 
	echo " -k  or stop     Stop Server" 
	echo " -i  or info     Show ServerInfo"
	echo " -h  or help     Get Some Info for the Script" 
}


#Main
case "$param_1" in 
	"start"|"-s")
		StartServer;;

	"stop"|"-k")
		StopServer;;
		
	"info"|"-i")
		Info;;

	"help"|"-h")
		Help;;		
esac
