#!/usr/bin/env bash

CURDIR=`pwd`
APPNAME=`pwd | awk -F'/' '{print $(NF)}'`
BAKGOPATH="$GOPATH"
export GOPATH="$CURDIR:$GOPATH"

echo 'GOPATH' `go env GOPATH`

gofmt -w src

DEBUG=''
case $2 in
	"-D")
	DEBUG='-gcflags "-N -l" -ldflags "-s"'
	echo $DEBUG
esac

case $1 in
	""|"-api")
		echo 'make apiserver'
		go clean apiserver
		go install apiserver
		echo 'make finished'
		;;
	
	"-init")
		echo 'init start...'
		echo "go get -u github.com/futurez/litego/config"
		go get -u github.com/futurez/litego/config
		echo "go get -u github.com/futurez/litego/httplib"
		go get -u github.com/futurez/litego/httplib
		echo "go get -u github.com/futurez/litego/logger"
		go get -u github.com/futurez/litego/logger
		echo "go get -u github.com/futurez/litego/mysqlpool"
		go get -u github.com/futurez/litego/mysqlpool
		echo "go get -u github.com/futurez/litego/util"
		go get -u github.com/futurez/litego/util
		echo 'init finished'
		;;

esac

export GOPATH="$BAKGOPATH"


